/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Shop = IDL.Record({
  'ownerName' : IDL.Text,
  'shopId' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'imageUrl' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'shopName' : IDL.Text,
  'category' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getShop' : IDL.Func([IDL.Text], [Shop], ['query']),
  'getShopsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
  'getShopsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
  'registerShop' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Shop = IDL.Record({
    'ownerName' : IDL.Text,
    'shopId' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'imageUrl' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'shopName' : IDL.Text,
    'category' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getShop' : IDL.Func([IDL.Text], [Shop], ['query']),
    'getShopsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
    'getShopsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Shop)], ['query']),
    'registerShop' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };